### ISSUE TITLE
Gallery slideshow too fast.

### ISSUE THREAD

**Issue by DavidBeeb** [simondotm/bbc-nula#3]
I have compiled a few slideshows using this tutorial and was wondering how to slow down the slideshow so the images stay on the screen longer.
I am able to edit the compile.py but could not find what to change.
Please tell me what to do.

Thanks for the easy to follow tutorial, had it working first go.

Thanks

**Comment by simondotm** [comment]
Hi!
Great to hear you've had success with a custom gallery! (do feel free to share, would love to see what other's have achieved with it!)

Great question on the timing - the quick answer is a bit hacky, but it'll work.

Take a look at `asm/main.asm`:
https://github.com/bitshifters/bbc-nula/blob/master/asm/main.asm

In here you'll see a few references to code like this:
```
	; wait for keypress within 2 secs
    lda #&81:ldx #200:ldy #0:jsr &fff4 ; osbyte
```

If you just duplicate these lines, you'll get 4 secs per pic instead of 2. eg.
```
	; wait for keypress within 2 secs
    lda #&81:ldx #200:ldy #0:jsr &fff4 ; osbyte
    lda #&81:ldx #200:ldy #0:jsr &fff4 ; osbyte
```

I should add a delay function really, so it's easier to set in one place.

Cheers
Simon

**Comment by DavidBeeb** [comment]
Here is my gallery.

**Comment by DavidBeeb** [comment]
Here is my gallery>

[sel1.zip](https://github.com/bitshifters/bbc-nula/files/3193670/sel1.zip)
